In [271]:
import pandas as pd
import numpy as np
import matplotlib as pyplot

In [272]:
input_1 = np.array([[0,1,0],[0,1,0],[0,1,0]])
input_2 = np.array([[1,1,1],[0,1,0],[1,1,1]])
input_3 = np.array([[1,1,1],[0,0,1],[0,0,1]])
input_4 = np.array([[1,0,1],[1,1,1],[0,0,1]])

# Print Input

In [273]:
input_1

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

# Shape of the Input

In [274]:
input_1.shape

(3, 3)

# Flattening the Input

In [275]:
def flattenInput(mat):
        mat = mat.flatten()
        mat = mat.reshape(mat.shape[0],1)
        return mat

flattenInput_ = flattenInput(input_1)

# Weight Initialization

In [276]:
def weightInitialization(type = "random"):
    if(type == "random"):
        initialWeights = np.random.random(size = (9,4))
    else:
        initialWeights = np.random.normal(size = (9,4))
    
    initialWeights = initialWeights.reshape(9,4)
    return initialWeights

In [277]:
weights = weightInitialization("random")

In [278]:
weights

array([[0.82755444, 0.8456071 , 0.60557598, 0.22609874],
       [0.75293716, 0.09851981, 0.6077168 , 0.7100797 ],
       [0.61220666, 0.83377502, 0.2534754 , 0.98061023],
       [0.11883868, 0.79966333, 0.30517174, 0.14091617],
       [0.88128317, 0.23194534, 0.55395444, 0.96146012],
       [0.58799042, 0.29805243, 0.67625967, 0.08289472],
       [0.7553429 , 0.69875351, 0.84272549, 0.85226495],
       [0.22451872, 0.48436359, 0.9194592 , 0.1128543 ],
       [0.80264717, 0.62445747, 0.88599917, 0.22230676]])

In [279]:
weights.shape

(9, 4)

# Manipulating the Array

In [280]:
def manipulatingTheArray(mat):
    mat = flattenInput(mat)
    
    for index in range(mat.shape[0]):    
        if mat[index] == 0:
            mat[index] = -1
    return mat

In [281]:
manipulatingTheArray(input_1)

array([[-1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [-1]])

# Thresholding Weight

In [346]:
def thresholding(out):
    
    for item in range(out.shape[1]):
        if out[0][item] > 0.8:
            out[0][item] = 0.8
        else:
            out[0][item] = -10
            
    return out
    

In [347]:
inputImage = [input_1,input_2,input_3,input_4]

# Weight Update

In [348]:
def weightUpdate(epoch,iteration,inputImage,weight):
    """
    Every epoch , We are doing iterations for every image in 
    the list
    """
    flattenImage = []
    for image_ in inputImage:
        image_ = flattenInput(image_)
        flattenImage.append(image_)

    for epoch_ in range(epoch):
            for input_ in flattenImage:
                input_ = manipulatingTheArray(input_)
                for iteration_ in range(iteration):
                    out = np.dot(input_.T , weight)
                    out = thresholding(out)
                    #manipulatedinput = manipulatingTheArray(input_)
                    weight = weight + np.dot(input_, out)
                print(out)
            

In [349]:
weightUpdate(1,10,inputImage,weights)

[[-10. -10. -10. -10.]]
[[-10. -10. -10. -10.]]
[[0.8 0.8 0.8 0.8]]
[[0.8 0.8 0.8 0.8]]


# Experimenting with the Weight Update Function 

1. Without Thresholding

In [350]:
def weightUpdateNoThresholding(epoch,iteration,inputImage,weight):
    """
    Every epoch , We are doing iterations for every image in 
    the list
    """
    flattenImage = []
    for image_ in inputImage:
        image_ = flattenInput(image_)
        flattenImage.append(image_)

    for epoch_ in range(epoch):
            for input_ in flattenImage:
                for iteration_ in range(iteration):
                    out = np.dot(input_.T , weight)
                    mInput = manipulatingTheArray(input_)
                    weight = weight + np.dot(mInput, out)
    
    return weight

In [351]:
print(weightUpdateNoThresholding(1,10,inputImage,weights))

[[-3.40422426e+29 -1.49232530e+29 -3.81153139e+29 -3.26806687e+29]
 [ 3.40422419e+29  1.49232527e+29  3.81153131e+29  3.26806681e+29]
 [-3.40422426e+29 -1.49232530e+29 -3.81153139e+29 -3.26806687e+29]
 [-3.40422419e+29 -1.49232527e+29 -3.81153131e+29 -3.26806681e+29]
 [-3.40422419e+29 -1.49232527e+29 -3.81153131e+29 -3.26806681e+29]
 [-3.40422426e+29 -1.49232530e+29 -3.81153139e+29 -3.26806687e+29]
 [ 3.40422426e+29  1.49232530e+29  3.81153139e+29  3.26806687e+29]
 [ 3.40422426e+29  1.49232530e+29  3.81153139e+29  3.26806687e+29]
 [-3.40422426e+29 -1.49232530e+29 -3.81153139e+29 -3.26806687e+29]]


2. No Input Manipulation

In [352]:
def weightUpdateNoInputManipulation(epoch,iteration,inputImage,weight):
    """
    Every epoch , We are doing iterations for every image in 
    the list
    """
    flattenImage = []
    for image_ in inputImage:
        image_ = flattenInput(image_)
        flattenImage.append(image_)

    for epoch_ in range(epoch):
            for input_ in flattenImage:
                for iteration_ in range(iteration):
                    out = np.dot(input_.T , weight)
                    out = thresholding(out)
                    weight = weight + np.dot(input_, out)

    return weight

In [353]:
print(weightUpdateNoInputManipulation(1,100,inputImage,weights))

[[240.82755444 240.8456071  240.60557598 240.22609874]
 [240.75293716 240.09851981 240.6077168  240.7100797 ]
 [240.61220666 240.83377502 240.2534754  240.98061023]
 [ 80.11883868  80.79966333  80.30517174  80.14091617]
 [240.88128317 240.23194534 240.55395444 240.96146012]
 [160.58799042 160.29805243 160.67625967 160.08289472]
 [ 80.7553429   80.69875351  80.84272549  80.85226495]
 [160.22451872 160.48436359 160.9194592  160.1128543 ]
 [240.80264717 240.62445747 240.88599917 240.22230676]]


3. Do combined Iteration for every image

In [354]:
def weightUpdateCombinedIterationForEveryImage(epoch,iteration,inputImage,weight):
    """
    Every epoch , We are doing iterations for every image in 
    the list
    """
    flattenImage = []
    for image_ in inputImage:
        image_ = flattenInput(image_)
        flattenImage.append(image_)

    for epoch_ in range(epoch):
        for iteration_ in range(iteration):
            for input_ in flattenImage:
                    out = np.dot(input_.T , weight)
                    out = thresholding(out)
                    weight = weight + np.dot(input_, out)

    return weight

In [355]:
print(weightUpdateCombinedIterationForEveryImage(1,10,inputImage,weights))

[[24.82755444 24.8456071  24.60557598 24.22609874]
 [24.75293716 24.09851981 24.6077168  24.7100797 ]
 [24.61220666 24.83377502 24.2534754  24.98061023]
 [ 8.11883868  8.79966333  8.30517174  8.14091617]
 [24.88128317 24.23194534 24.55395444 24.96146012]
 [16.58799042 16.29805243 16.67625967 16.08289472]
 [ 8.7553429   8.69875351  8.84272549  8.85226495]
 [16.22451872 16.48436359 16.9194592  16.1128543 ]
 [24.80264717 24.62445747 24.88599917 24.22230676]]


4. Changing the input to 0 to -1

In [356]:
def weightUpdateCombinedIterationForEveryImage(epoch,iteration,inputImage,weight):
    """
    Every epoch , We are doing iterations for every image in 
    the list
    """
    flattenImage = []
    for image_ in inputImage:
        image_ = flattenInput(image_)
        flattenImage.append(image_)

    for epoch_ in range(epoch):
        for iteration_ in range(iteration):
            for input_ in flattenImage:
                    input_ = manipulatingTheArray(input_)
                    out = np.dot(input_.T , weight)
                    out = thresholding(out)
                    weight = weight + np.dot(input_, out)

    return weight

In [357]:
finalWeight = weightUpdateCombinedIterationForEveryImage(1,10,inputImage,weights)

In [358]:
for item in inputImage:
    item = flattenInput(item)
    item = manipulatingTheArray(item)
    print(np.dot(item.T,finalWeight))

[[-1065.84584122 -1067.28548012 -1065.48807701 -1064.72069746]]
[[-995.85033885 -997.28029391 -996.31252491 -996.15813609]]
[[297.60335239 296.48568605 296.40771615 296.15449463]]
[[698.09772176 698.35186377 696.91053491 696.93908779]]


In [359]:
finalWeight

array([[  16.82755444,   16.8456071 ,   16.60557598,   16.22609874],
       [-199.24706284, -199.90148019, -199.3922832 , -199.2899203 ],
       [  16.61220666,   16.83377502,   16.2534754 ,   16.98061023],
       [ 200.11883868,  200.79966333,  200.30517174,  200.14091617],
       [-199.11871683, -199.76805466, -199.44604556, -199.03853988],
       [ 216.58799042,  216.29805243,  216.67625967,  216.08289472],
       [ -15.2446571 ,  -15.30124649,  -15.15727451,  -15.14773505],
       [-215.77548128, -215.51563641, -215.0805408 , -215.8871457 ],
       [  16.80264717,   16.62445747,   16.88599917,   16.22230676]])