In [13]:
import pandas as pd
import numpy as np
import matplotlib as pyplot

In [14]:
input_1 = np.array([[0,1,0],[0,1,0],[0,1,0]])
input_2 = np.array([[1,1,1],[0,1,0],[1,1,1]])
input_3 = np.array([[1,1,1],[0,0,1],[0,0,1]])
input_4 = np.array([[1,0,1],[1,1,1],[0,0,1]])

# Print Input

In [18]:
input_1

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

# Shape of the Input

In [19]:
input_1.shape

(3, 3)

# Flattening the Input

In [93]:
def flattenInput(mat):
        mat = mat.flatten()
        mat = mat.reshape(mat.shape[0],1)
        return mat

flattenInput_ = flattenInput(input_1)

# Weight Initialization

In [94]:
def weightInitialization(type = "random"):
    if(type == "random"):
        initialWeights = np.random.random(size = (9,4))
    else:
        initialWeights = np.random.normal(size = (9,4))
    
    initialWeights = initialWeights.reshape(9,4)
    return initialWeights

In [95]:
weights = weightInitialization("random")

In [96]:
weights

array([[0.36285853, 0.52483573, 0.49826119, 0.11927936],
       [0.60166989, 0.10080622, 0.22590126, 0.96678413],
       [0.13224824, 0.90745252, 0.26729121, 0.57112392],
       [0.46983777, 0.81156609, 0.60615638, 0.74292144],
       [0.00388488, 0.42398963, 0.18058268, 0.04204677],
       [0.89911768, 0.01086082, 0.23060321, 0.62445653],
       [0.1653292 , 0.49343422, 0.40717113, 0.32882756],
       [0.70733165, 0.76490453, 0.80887864, 0.33398016],
       [0.51977209, 0.70750114, 0.40061724, 0.34351531]])

In [97]:
weights.shape

(9, 4)

# Manipulating the Array

In [159]:
def manipulatingTheArray(mat):
    mat = flattenInput(mat)
    
    for index in range(mat.shape[0]):    
        if mat[index] == 0:
            mat[index] = -1
    return mat

In [160]:
manipulatingTheArray(input_1)

array([[-1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [-1],
       [-1],
       [ 1],
       [-1]])

# Thresholding Weight

In [200]:
def thresholding(out):
    
    for item in range(out.shape[1]):
        if out[0][item] > 0.5:
            out[0][item] = 0.5
        else:
            out[0][item] = -0.1
            
    return out
    

In [201]:
inputImage = [input_1,input_2,input_3,input_4]

# Weight Update

In [202]:
def weightUpdate(epoch,iteration,inputImage,weight):
    """
    Every epoch , We are doing iterations for every image in 
    the list
    """
    flattenImage = []
    for image_ in inputImage:
        image_ = flattenInput(image_)
        flattenImage.append(image_)

    for epoch_ in range(epoch):
            for input_ in flattenImage:
                for iteration_ in range(iteration):
                    out = np.dot(input_.T , weight)
                    out = thresholding(out)
                    manipulatedinput = manipulatingTheArray(input_)
                    weight = weight + np.dot(manipulatedinput , out)
                print(out)
            

In [203]:
weightUpdate(1,5,inputImage,weights)

[[0.5 0.5 0.5 0.5]]
[[-0.1  0.5 -0.1 -0.1]]
[[-0.1  0.5 -0.1 -0.1]]
[[-0.1  0.5 -0.1 -0.1]]
